// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaN6l0gS39Xuh8Orf8tmuTYOJiBuFz7gE',
    appId: '1:52215147179:web:cb4feff245702bbd56a5ee',
    messagingSenderId: '52215147179',
    projectId: 'smart-shopping-app-12cfd',
    authDomain: 'smart-shopping-app-12cfd.firebaseapp.com',
    databaseURL: 'https://smart-shopping-app-12cfd-default-rtdb.firebaseio.com',
    storageBucket: 'smart-shopping-app-12cfd.firebasestorage.app',
    measurementId: 'G-B7J8FNG28Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxvOTIkP_RK_4CTuLPtJrN7raAKtA7lDY',
    appId: '1:52215147179:android:13b7af845e1d415d56a5ee',
    messagingSenderId: '52215147179',
    projectId: 'smart-shopping-app-12cfd',
    databaseURL: 'https://smart-shopping-app-12cfd-default-rtdb.firebaseio.com',
    storageBucket: 'smart-shopping-app-12cfd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaN6l0gS39Xuh8Orf8tmuTYOJiBuFz7gE',
    appId: '1:52215147179:web:d060b6ec6ffc493f56a5ee',
    messagingSenderId: '52215147179',
    projectId: 'smart-shopping-app-12cfd',
    authDomain: 'smart-shopping-app-12cfd.firebaseapp.com',
    databaseURL: 'https://smart-shopping-app-12cfd-default-rtdb.firebaseio.com',
    storageBucket: 'smart-shopping-app-12cfd.firebasestorage.app',
    measurementId: 'G-XK3434HFBE',
  );

}